# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MDB_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env

volumes:
  mongodb_data_container: